### ISSUE TITLE
No readme

### ISSUE THREAD

**Issue by FROL256** [Mrkol/thesis_vgi#1]
Readme with brief description and build instruction would be nice to have

Build sequence is unknown: 

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

**Comment by Mrkol** [comment]
Readme with build instructions added
